<?php

Config::write('Segment', array(
	//'aboutUsUrl' => '',
	// 'blogUrl' => '',
	'contactMail' => 'contact@meumobi.com',
	// 'contactPhone' => '',
	'contactFacebook' => 'http://facebook.com/meumobi',
	'contactTwitter' => 'http://twitter.com/meumobi',
	'id' => 'meumobi',
	'domain' => 'meumobi.com',
	'title' => 'MeuMobi',
	'root' => 'Items',
	'items' =>  ['articles', 'events', 'merchant_products', 'promotions', 'products', 'stores', 'files', 'contacts', 'polls'],
	'extensions' => ['rss', 'store-locator', 'event-feed','google-merchant-feed'],
	'email' => ['no-reply@meumobi.com' => 'MeuMobi'],
	'hideCategories' => false,
	'enableSignup' => false,
	'fullOptions' => false,
	'enableMultiUsers' => Config::read('App.environment') != 'production',
	'analytics' => 'UA-22519238-3',
	'themes' => Config::read('App.environment') == 'production' ? array('paraty', 'posto9', 'leblon', 'helmut', 'flip', 'rimobi') : [],
	'enableFieldSet' => array('photos', 'visitors', 'weblinks','location', 'contact', 'news', 'description', 'timetable'), //, 'stocks'),
	'enableApiAccessFromAllDomains' => true,
));
