source 'http://rubygems.org'

gem 'capistrano', '~> 3.2.1'
gem 'capistrano-bundler'
gem 'thor', '~> 0.14'
gem 'activesupport', '~> 3.2.6'
gem 'whenever', '~> 0.7.3', require: false
gem 'sass', '~> 3.2.0', require: false
gem 'mongo', '~> 1.8.5'
gem 'redcarpet', '~> 2.3.0'
